spring:
  application:
    name: consumer-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: user-order-alias:org.surro.consumerservice.model.UserOrder
            trusted:
              packages: org.surro.consumerservice.model, org.surro.producerservice.model
server:
  port: 8081
