spring:
  application:
    name: producer-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: user-order-alias:org.surro.producerservice.model.UserOrder

server:
  port: 8082
